id: I9D6405E4
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 14:56:24.172194
last_modified: 2023-02-08 14:56:24.172387
source_metadata:
  title: Bodhisatvacaryānirdeśa
  language: bo
bases:
  BC36:
    base_file: BC36.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
